version: '3.4'

services:
  rails:
    image: rails
    volumes:
      - ./blog:/app
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "bundle exec rails server -p 3000 -b '0.0.0.0'"